version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - card_trx_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "cardtrx"
      POSTGRES_USER: "cardtrxuser"
      POSTGRES_PASSWORD: "zruQQNDVrxJvvo"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cardtrxuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cardtrx
      - SPRING_DATASOURCE_USERNAME=cardtrxuser
      - SPRING_DATASOURCE_PASSWORD=zruQQNDVrxJvvo

volumes:
  card_trx_data:
    driver: local