spring:
  application:
    name: CARD-TRX
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  datasource:
    url: jdbc:postgresql://localhost:5432/cardtrx
    username: cardtrxuser
    password: zruQQNDVrxJvvo
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
      auto-commit: false
      connection-test-query: SELECT 1
      idle-timeout: 120000
      minimum-idle: 10
      maximum-pool-size: 30
      connection-timeout: 300
      max-lifetime: 9000
      validation-timeout: 2000
      leak-detection-threshold: 5000
  ##Jpa configurations
  jpa:
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:5000}


#Actuator
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['health']
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /v3/api-docs
